name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run tests
      run: sudo bash -x ./tests/run-tests.sh
      continue-on-error: true

    - name: Print current file states
      run: |
        echo Listing /etc/environment...
        ls -lah /etc/environment
        cat /etc/environment
        echo Listing /etc/ssh/ssh_config.d/...
        ls -lah /etc/ssh/ssh_config.d
        echo Listing /etc/systemd/timesyncd.conf...
        ls -lah /etc/systemd/timesyncd.conf
        cat /etc/systemd/timesyncd.conf
      continue-on-error: true

    - name: Test report
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Test Results
        path: tests/report.json
        reporter: mocha-json
        
    - name: Upload test report as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report
        path: tests/report.json
        retention-days: 30

